# some good tips can be founded in: https://www.reddit.com/r/HelixEditor/comments/1iearpt/could_you_kindly_share_any_new_tricks_or/

[editor]
mouse = false
middle-click-paste = false
shell = ["nu", "-c"]
line-number = "relative"
cursorline = true
rulers = [80]
bufferline = "multiple"
completion-replace = true
end-of-line-diagnostics = "error"
continue-comments = false
jump-label-alphabet = "jfkdls;aurieowpqnvmcxz"
text-width = 110

[editor.statusline]
left = [
  "mode",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator",
  "selections",
  "position",
  "total-line-numbers",
]
right = [
  "file-encoding",
  "spinner",
  "spacer",
  "diagnostics",
  "register",
  "version-control",
  "file-encoding",
  "file-type",
  "workspace-diagnostics",
]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true
wrap-at-text-width = true

[editor.inline-diagnostics]
cursor-line = "error"

# remap keybinding for better
[keys.insert.j]
k = "normal_mode" # Maps `jk` to exit insert mode

# better work with project
[keys.normal.space]
B = "file_picker_in_current_buffer_directory"
f = "file_picker_in_current_directory"
F = "file_picker"
r = ":reload"
R = "rename_symbol"
x = ":bclose"

[keys.normal]
R = "replace_selections_with_clipboard"
y = ["yank_main_selection_to_clipboard"]
d = ["yank_main_selection_to_clipboard", "delete_selection"]
p = ["paste_clipboard_after"]
P = ["paste_clipboard_before"]
X = "extend_line_above"                                                 # inverse of x 
"C-c" = ["collapse_selection", "keep_primary_selection", "normal_mode"]
"ret" = "goto_word"
"J" = "goto_previous_buffer"
"K" = "goto_next_buffer"
"C-s" = ":write"
# source: https://github.com/helix-editor/helix/discussions/5764
"A-j" = ["extend_to_line_bounds", "delete_selection", "paste_after"]
"A-k" = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
# disable some key bindings
esc = "no_op"
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"

[keys.insert]
"C-s" = ["normal_mode", ":write"]
"C-c" = ["collapse_selection", "keep_primary_selection", "normal_mode"]
"C-e" = "delete_char_backward"
# disable some key bindings
esc = "no_op"
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
backspace = "no_op"

[keys.select]
y = ["yank_main_selection_to_clipboard"]
d = ["yank_main_selection_to_clipboard", "delete_selection"]
"C-c" = ["collapse_selection", "keep_primary_selection", "normal_mode"]
"ret" = "extend_to_word"
# disable some key bindings
esc = "no_op"

[keys.normal.g]
# disable some key bindings
n = "no_op"
p = "no_op"
