[go-home]
mon = [{ after = '18:30', before = '5:30' }]
tue = [{ after = '18:30', before = '5:30' }]
wed = [{ after = '18:30', before = '5:30' }]
thu = [{ after = '18:30', before = '5:30' }]
fri = [{ after = '18:30', before = '5:30' }]
sat = [{ after = '18:30', before = '5:30' }]
sun = [{ after = '18:30', before = '5:30' }]

[not-social-networks]
mon = [{ after = '6:00', before = '16:00' }]
tue = [{ after = '6:00', before = '16:00' }]
wed = [{ after = '6:00', before = '16:00' }]
thu = [{ after = '6:00', before = '16:00' }]
fri = [{ after = '6:00', before = '16:00' }]
sat = [{ after = '6:00', before = '16:00' }]
sun = [{ after = '6:00', before = '16:00' }]
